# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38802e94979063b3058ec9213df2af3a5f239b30085e1083a22ca1e27bb905f55dee820c2bdccaa8ac5304e6d1c56e404a85dff717b2fa1de18ce15a6f97ea32

test:
  secret_key_base: c1ea28be9a6375756546c3a80c7a75e0653512c120068b9854487306b12d949b6ee918bc15a67d91e76ce91dbf616dff57714809f4823fcac687318fd8c6cb41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
